version: '3.8'
services:
  petbook-be:
    image: petbook-be:0.0.1
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    environment:
      - TEST=aaaa
    volumes:
      - ..:/workspace
    command: sleep infinity